### ISSUE TITLE
thesis

### ISSUE THREAD

**Issue by Maritime-Moon** [Maelic/SGG-Benchmark#24]
Can you tell me where your paper ended up?

**Comment by Maelic** [comment]
Hi, if you are talking about the real-time SGG paper, I haven't published it yet because I am wrapping up my thesis at this point and I have other projects on the go. I may publish it later on.
In the meantime, if you find my work useful for your research, you can cite the Arxiv version in your work.

**Comment by Maritime-Moon** [comment]
Can you tell me a little bit about the Arxiv version?

**Comment by Maelic** [comment]
[https://arxiv.org/abs/2405.16116](https://arxiv.org/abs/2405.16116)
