### ISSUE TITLE
I want use my own dataset

### ISSUE THREAD

**Issue by Quan-zzx** [Maelic/SGG-Benchmark#25]
Hello, I trained a Faster RCNN on my own dataset. How can I use your framework to achieve relationship prediction? Should I retrain or can I use it directly?
Can you give me a brief step-by-step explanation?
Thank you very much

**Comment by Maelic** [comment]
Hello, if you want to train a model for relationship prediction you need to have an annotated dataset with relations between objects. The easiest way to do so is to use [this tool](https://github.com/Milomilo0320/A-Semi-automatic-Annotation-Software-for-Scene-Graph) to annotate some images with your classes. Alternatively, you can use the Visual Genome dataset as based annotations and re-process them to fit your requirements. I made some scripts that could be useful for that [here](https://github.com/Maelic/VG_curated/tree/main/dataset_generation) (there is no documentation for this procedure for now).
Best

**Comment by Quan-zzx** [comment]
thanks!

> Hello, if you want to train a model for relationship prediction you need to have an annotated dataset with relations between objects. The easiest way to do so is to use [this tool](https://github.com/Milomilo0320/A-Semi-automatic-Annotation-Software-for-Scene-Graph) to annotate some images with your classes. Alternatively, you can use the Visual Genome dataset as based annotations and re-process them to fit your requirements. I made some scripts that could be useful for that [here](https://github.com/Maelic/VG_curated/tree/main/dataset_generation) (there is no documentation for this procedure for now). Best

**Comment by wangjanice8** [comment]
> Hello, I trained a Faster RCNN on my own dataset. How can I use your framework to achieve relationship prediction? Should I retrain or can I use it directly? Can you give me a brief step-by-step explanation? Thank you very much

Hi,
I noticed you had a similar issue [link to the relevant connection]. I was wondering if you've managed to solve it? The link contains documentation for some scripts, which I hope might be helpful to you.
I'm currently creating a dataset using local images. I'm confused about what information regarding these images should be included in the image_data.json. The VG dataset has the following structure:
Width: 800
URL: https://cs.stanford.edu/people/rak248/VG_100K_2/1.jpg
Height: 600
Image ID: 1
COCO ID: None
Flickr ID: None
Anti Prop: 0.0
However, I don't have the URL information since my images are local. I'm wondering if this URL field (and other fields like COCO ID, Flickr ID) is mandatory? If not, what are the essential fields I should include for local images in the image_data.json for the dataset to work properly?
Thanks in advance for any insights!

**Comment by wangjanice8** [comment]
> Hello, I trained a Faster RCNN on my own dataset. How can I use your framework to achieve relationship prediction? Should I retrain or can I use it directly? Can you give me a brief step-by-step explanation? Thank you very much

Hi,
I noticed you had a similar issue . I was wondering if you've managed to solve it? The link contains documentation for some scripts （https://github.com/danfeiX/scene-graph-TF-release/tree/master/data_tools）, which I hope might be helpful to you.
I'm currently creating a dataset using local images. I'm confused about what information regarding these images should be included in the image_data.json. The VG dataset has the following structure:
Width: 800
URL: https://cs.stanford.edu/people/rak248/VG_100K_2/1.jpg
Height: 600
Image ID: 1
COCO ID: None
Flickr ID: None
Anti Prop: 0.0
However, I don't have the URL information since my images are local. I'm wondering if this URL field (and other fields like COCO ID, Flickr ID) is mandatory? If not, what are the essential fields I should include for local images in the image_data.json for the dataset to work properly?
Thanks in advance for any insights!

**Comment by harvey-ph** [comment]
> Hello, if you want to train a model for relationship prediction you need to have an annotated dataset with relations between objects. The easiest way to do so is to use [this tool](https://github.com/Milomilo0320/A-Semi-automatic-Annotation-Software-for-Scene-Graph) to annotate some images with your classes. Alternatively, you can use the Visual Genome dataset as based annotations and re-process them to fit your requirements. I made some scripts that could be useful for that [here](https://github.com/Maelic/VG_curated/tree/main/dataset_generation) (there is no documentation for this procedure for now). Best

Hi, for the SGDET task, I had my own datasets annotated including boxes_1024, boxes_512, attributes, relationships and labels, do I need anything else or just it?
