### ISSUE TITLE
Can train normally, but run out of memory during val.

### ISSUE THREAD

**Issue by Quan-zzx** [Maelic/SGG-Benchmark#26]
Hello，I encountered a problem during training. The following is my command.
` python SGG-Benchmark/tools/relation_train_net.py --task sgdet --save-best --config-file "SGG-Benchmark\configs\VG150\e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR VCTreePredictor SOLVER.IMS_PER_BATCH 1 TEST.IMS_PER_BATCH 1 DTYPE "float16" SOLVER.MAX_EPOCH 20 MODEL.PRETRAINED_DETECTOR_CKPT epoch_60.pth OUTPUT_DIR output/`

I can train normally, but I run out of memory during validation.
After my investigation, I found that the problem occurs .[in this file](https://github.com/Maelic/SGG-Benchmark/blob/main/sgg_benchmark/modeling/poolers.py)
![image](https://github.com/user-attachments/assets/a3252750-3d76-45b3-b8a8-5d9bbcdd6170)
At line 123 of this file, it creates a very large result vector, which leads to running out of GPU memory. At this point, the size of outsize is as high as two hundred thousand. This should not be normal, but I don’t know how to solve this problem.

**Comment by Maelic** [comment]
Hello @Quan-zzx, 
I don't have this problem on my machine (I use one Nvidia A6000 GPU with 42GB of memory). I know the VCTree model is more memory-hungry than the others but this should not happen in the pooling function which creates tensors only by batches. 
Which tensor exactly has a size of two hundred thousand? Can you post the logs of your experiments?

As a workaround, you can reduce the number of proposals used during training with the variable MODEL.ROI_HEADS.DETECTIONS_PER_IMG. You can reduce this down to 30-40 and you should not see a big drop in performance (if you want more details I have drawn a scaling law in the ablation studies of my paper [here](https://arxiv.org/pdf/2405.16116)).
Using YOLOV8 instead of Faster-RCNN may also significantly reduce memory usage (especially in the pooler).

**Comment by Quan-zzx** [comment]
> Hello @Quan-zzx, I don't have this problem on my machine (I use one Nvidia A6000 GPU with 42GB of memory). I know the VCTree model is more memory-hungry than the others but this should not happen in the pooling function which creates tensors only by batches. Which tensor exactly has a size of two hundred thousand? Can you post the logs of your experiments?
> 
> As a workaround, you can reduce the number of proposals used during training with the variable MODEL.ROI_HEADS.DETECTIONS_PER_IMG. You can reduce this down to 30-40 and you should not see a big drop in performance (if you want more details I have drawn a scaling law in the ablation studies of my paper [here](https://arxiv.org/pdf/2405.16116)). Using YOLOV8 instead of Faster-RCNN may also significantly reduce memory usage (especially in the pooler).

Thank you for your reply. As shown in the picture below, I have printed the shape of the result that I want to set. The num_rois is very large，
![image](https://github.com/user-attachments/assets/d0161943-ed05-4549-8c40-fc4230270a9b)
![image](https://github.com/user-attachments/assets/a9c71c3a-2f7e-492e-b48e-811382db9fd4)
![image](https://github.com/user-attachments/assets/bcf57309-a8c0-4213-9e73-2aa3ddfb1a95)


The second image shows that it wanted to create a tensor of 263682 * 1024 * 7 * 7, but unfortunately failed because it exceeded the GPU memory of over 40GB.
But this only happens during validation, I can train normally。As shown in the figure below, I printed the situation during training, and the number of ROIs is only a few thousand
![image](https://github.com/user-attachments/assets/0de04a3f-ec42-4957-9450-b3de0e2123fe)

**Comment by Quan-zzx** [comment]
> Hum that's really weird, can you give me your `e2e_relation_X_101_32_8_FPN_1x.yaml` file so I can try to reproduce the problem? For the pre-trained Faster-RCNN detector, are you using your own weights?

Maybe there's a problem with my pre trained model. My previous model was trained by MMDetection, and I just tried your code to train it, so the problem I mentioned won't occur anymore

**Comment by Maelic** [comment]
Yes if you trained the backbone with another framework, it is likely to fail to work here. It only works for YOLOV8 because I am using the ultralytics implementation directly.
If you want to load your backbone with the MMDet implementation correctly, you will need to add a new backbone class [here](https://github.com/Maelic/SGG-Benchmark/blob/main/sgg_benchmark/modeling/backbone/backbone.py) and modify the default arguments. For Faster-RCNN you could register for instance a "R-101-FPN-MMDet" class. You will then have to modify the [overall structure](https://github.com/Maelic/SGG-Benchmark/blob/main/sgg_benchmark/modeling/detector/generalized_rcnn.py) to fit it to your new backbone structure (with appropriate names).

**Comment by Quan-zzx** [comment]
> Yes if you trained the backbone with another framework, it is likely to fail to work here. It only works for YOLOV8 because I am using the ultralytics implementation directly. If you want to load your backbone with the MMDet implementation correctly, you will need to add a new backbone class [here](https://github.com/Maelic/SGG-Benchmark/blob/main/sgg_benchmark/modeling/backbone/backbone.py) and modify the default arguments. For Faster-RCNN you could register for instance a "R-101-FPN-MMDet" class. You will then have to modify the [overall structure](https://github.com/Maelic/SGG-Benchmark/blob/main/sgg_benchmark/modeling/detector/generalized_rcnn.py) to fit it to your new backbone structure (with appropriate names).

OK,Tranks. I have used your code to train my object detection network and the results are good.

**Comment by Maelic** [comment]
Closing as resolved
