### ISSUE TITLE
Missing "Bed" Category in IndoorVG

### ISSUE THREAD

**Issue by Catchip** [Maelic/SGG-Benchmark#41]
I am currently working on inferring scene categories based on scene graphs, and I noticed that you don’t have the "Bed" category in IndoorVG while it is present in VG150. From my understanding, bed is a very common indoor object. For what purpose was it removed?

**Comment by Maelic** [comment]
That's a good question, long story short the reason is that I wanted to create a data split with the highest inter-connectivity between object classes (see [this for reference](https://openaccess.thecvf.com/content/ICCV2023W/SG2RL/papers/Neau_Fine-Grained_is_Too_Coarse_A_Novel_Data-Centric_Approach_for_Efficient_ICCVW_2023_paper.pdf)) with a good diversity in terms of relation types (spatial, semantic etc...). However, some classes were hindering a bit this balance so I removed them. 
But if you want to use IndoorVG in your application, you'd better use this split of the data which contains more classes (including the bed class):

[indoorvg_v3.zip](https://github.com/user-attachments/files/17741329/indoorvg_v3.zip)

**Comment by Catchip** [comment]
Thank you very much for your response. I will try using the additional dataset you provided. Additionally, for those who might be interested in this dataset in the future, here is a list of the classes it contains:
```python
{
'1': 'bag',
'2': 'bar',
'3': 'basket',
'4': 'bathtub',
'5': 'bed',
'6': 'blanket',
'7': 'blind',
'8': 'board',
'9': 'book',
'10': 'bookshelf',
'11': 'bottle',
'12': 'bowl',
'13': 'box',
'14': 'brick',
'15': 'button',
'16': 'cabinet',
'17': 'can',
'18': 'candle',
'19': 'carpet',
'20': 'cat',
'21': 'ceiling',
'22': 'chair',
'23': 'child',
'24': 'clock',
'25': 'computer',
'26': 'container',
'27': 'cord',
'28': 'couch',
'29': 'counter',
'30': 'cup',
'31': 'curtain',
'32': 'cushion',
'33': 'design',
'34': 'desk',
'35': 'dog',
'36': 'door',
'37': 'drawer',
'38': 'fan',
'39': 'faucet',
'40': 'floor',
'41': 'flower',
'42': 'food',
'43': 'frame',
'44': 'glass',
'45': 'hand',
'46': 'handle',
'47': 'head',
'48': 'headboard',
'49': 'holder',
'50': 'jacket',
'51': 'jar',
'52': 'key',
'53': 'keyboard',
'54': 'knob',
'55': 'lamp',
'56': 'laptop',
'57': 'leaf',
'58': 'leg',
'59': 'lid',
'60': 'light',
'61': 'luggage',
'62': 'magazine',
'63': 'microwave',
'64': 'mirror',
'65': 'monitor',
'66': 'mouse',
'67': 'mug',
'68': 'outlet',
'69': 'oven',
'70': 'painting',
'71': 'paper',
'72': 'pen',
'73': 'person',
'74': 'phone',
'75': 'pillow',
'76': 'plant',
'77': 'plate',
'78': 'poster',
'79': 'pot',
'80': 'rack',
'81': 'refrigerator',
'82': 'remote',
'83': 'rug',
'84': 'scissors',
'85': 'screen',
'86': 'seat',
'87': 'sheet',
'88': 'shelf',
'89': 'shirt',
'90': 'shoe',
'91': 'shower',
'92': 'sink',
'93': 'speaker',
'94': 'stand',
'95': 'stove',
'96': 'suitcase',
'97': 'table',
'98': 'teddy bear',
'99': 'television',
'100': 'tile',
'101': 'toilet',
'102': 'toilet paper',
'103': 'toothbrush',
'104': 'towel',
'105': 'toy',
'106': 'urinal',
'107': 'vase',
'108': 'vent',
'109': 'wall',
'110': 'window'
}
```
