### ISSUE TITLE
REACT mode is more likely aligned with the 'Scene Graph Classification (sgcls)' task？

### ISSUE THREAD

**Issue by Bobbypower** [Maelic/SGG-Benchmark#45]
react   sgcls mode?

**Comment by Maelic** [comment]
Hello, 

Currently, the SGCLS setting is not supported for the REACT model or any YOLO-based models (which I call Decoupled Two-Stage models). The reason behind that is that YOLO is a single-stage detector that decodes the bounding boxes AND the class labels at the same time, making it impossible to use the label classifier with the groundtruth boxes as it is the case in SGCLS.
In my opinion, the SGCLS task does not make any sense in Two-Stage SGG because the prediction of object labels seems to be worse after the relation prediction stage than before (which I discuss in Table 1 of [my paper](https://arxiv.org/pdf/2405.16116)).
